

export class ShopCartConstants{
  /**
   * Describe of checkbox.
   */
  static readonly CHECKBOX: string = 'checkbox';

  /**
   * Describe of checkbox group.
   */
  static readonly CHECKBOX_GROUP: string = 'checkboxGroup';

  /**
   * CommodityDetailPage url.
   */
  static readonly COMMODITY_DETAIL_PAGE_URL: string = 'pages/CommodityDetailPage';

  /**
   * ConfirmOrderPage url.
   */
  static readonly CONFIRM_ORDER_PAGE_URL: string = 'pages/ConfirmOrderPage';
}